<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4586d4a34ec719695f93bd33834e9b94
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Pelago\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Pelago\\' => 
        array (
            0 => __DIR__ . '/..' . '/pelago/emogrifier/Classes',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4586d4a34ec719695f93bd33834e9b94::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4586d4a34ec719695f93bd33834e9b94::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
